### ISSUE TITLE
Rendering of large graphs not displayed correctly

### ISSUE THREAD

**Issue by premsa** [recap-utr/arguebuf-python#1]
__Problem__: I use the visualization function to debugg my processing programs when needed. In most cases graphs are complete and I can zoom onto specific nodes, observing schemes and text. For large graphs the output is rendered outside of the PDF page which makes it difficult to research ideas. For the specific graph 1379, the visualization is cut to the right side. 

**Dataset**: "1379.json" (Kialo, not public)

**Code**:
``` 
graph = Graph.open(Path("1379.json"))
graph.render(Path("1379"),format='pdf')
``` 
**Result**:
![image](https://user-images.githubusercontent.com/38909445/103541898-6584d180-4e9c-11eb-93ec-0c7d37636926.png)

**Comment by mirkolenz** [comment]
Is this bug still relevant with the newest version? Possible mitigations might be the use of `png` output instead of `pdf` and setting `nodesep` in the `render` method. The underlying source of this issue seems to be in the graphviz library itself, so I am not sure we can do much about it.

**Comment by mirkolenz** [comment]
I am going to close this now, feel free to reopen if this is still an issue.
